---
title: "Nhanes Weight Models"
author: "Sarah Van Alsten"
date: "1/16/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(descr)
library(tidyverse)
library(MASS)
library(corrplot)
library(polycor)
library(survey)
library(nnet) #for multinomial logit
library(broom)
library(stargazer)



#read in the data
dat <- readr::read_csv("C:\\Users\\Owner\\OneDrive\\Documents\\Duncan_Lab_2018\\NHANES_WeightPerception\\NHANES_wt\\data\\12092019nhanes.csv")

#Smoking
dat <-
  dat %>%
  mutate(smoke100 = ifelse(SMQ020 %in% c(9,7,NA), NA,
                           ifelse(SMQ020 == 1, 1, 0))) %>%
  mutate(nowSmoke = ifelse(SMQ040 %in% c(9,7, NA), NA,
                           ifelse(SMQ040 == 3, 0, 1))) %>%
  mutate(smkStat = ifelse(smoke100 == 0, 0, #never
                          ifelse(nowSmoke == 0 & smoke100 == 1, 1, 
                                 ifelse(nowSmoke == 1, 2, NA)))) #former


dat$consid <- relevel(factor(dat$ConsiderWt,
                             labels = c("too thin", "about right", "too big")),
                      ref = "about right")
dat$likeTo = relevel(factor(dat$LikeToWeigh, 
                            labels = c("like to weigh less", "like to weigh same", "like to weigh more")),
                     ref = "like to weigh same")

dat$doingWt = relevel(factor(dat$doingAbtWt, labels = c("lost weight: intentional", "lost weight: unintented",
                                                    "tried to lose weight (but didnt)", "tried to not gain",
                                                    "doing nothing")),
                             ref = "doing nothing")

svy <- svydesign(id = ~SDMVPSU, 
                 strata = ~SDMVSTRA, 
                 weights = ~WTMEC6YR, 
                 nest = TRUE, 
                 data = dat)


```


##Crosstabs
```{r, echo = FALSE}

# Correlations/Crosstabs ------------------------------------------------------------
#First, just do the crosstabs (without survey adjustment)
CrossTable(dat$BMIcat, dat$LikeToWeigh, chisq = T)
CrossTable(dat$BMIcat, dat$doingAbtWt, chisq = T)
CrossTable(dat$BMIcat, dat$ConsiderWt, chisq = T)
CrossTable(dat$LikeToWeigh, dat$doingAbtWt, chisq = T)
CrossTable(dat$LikeToWeigh, dat$ConsiderWt, chisq = T)
CrossTable(dat$doingAbtWt, dat$ConsiderWt, chisq = T)


```

## Correlations and Strength of Association
```{r}

#polychoric correlation can be used for ordinal vars
#or Kendall's tau
cor.test(dat$BMIcat, dat$LikeToWeigh, method = "kendall")
polychor(dat$BMIcat, dat$LikeToWeigh, std.err = T) #-0.707

cor.test(dat$BMIcat, dat$ConsiderWt, method = "kendall")
polychor(dat$BMIcat, dat$ConsiderWt, std.err = T) #0.7403

cor.test(dat$ConsiderWt, dat$LikeToWeigh, method = "kendall")
polychor(dat$ConsiderWt, dat$LikeToWeigh, std.err = T) #-0.8913

polychor(dat$ConsiderWt, dat$doingAbtWt, std.err =T)
polychor(dat$LikeToWeigh, dat$doingAbtWt, std.err = T)
polychor(dat$BMIcat, dat$doingAbtWt, std.err = T)


#for nominal... already had chisq, get the cramer's v for strength of assoc
lsr::cramersV(dat$BMIcat, dat$doingAbtWt) #0.175
lsr::cramersV(dat$LikeToWeigh, dat$doingAbtWt) #0.355
lsr::cramersV(dat$ConsiderWt, dat$doingAbtWt) #0.312
```

##Regression

```{r}
#unadjusted odds for depression
dep1.ltw <- glm(depressionBinary ~ likeTo, #ref = same
                data = dat,
                family = binomial(link = "logit"))
summary(dep1.ltw)

dep1.cow <- glm(depressionBinary ~ consid, #ref = about right
                data = dat,
                family = binomial(link = "logit"))
summary(dep1.cow)

dep1.daw <- glm(depressionBinary ~ doingWt, #ref = not doing anything
                data = dat,
                family = binomial(link = "logit"))
summary(dep1.daw)
################################################################################################
#add in BMI category
dep2.ltw <- glm(depressionBinary ~ likeTo + factor(BMIcat), 
                data = dat,
                family = binomial(link = "logit"))
summary(dep2.ltw)

dep2.cow <- glm(depressionBinary ~ consid + factor(BMIcat), 
                data = dat,
                family = binomial(link = "logit"))
summary(dep2.cow)

dep2.daw <- glm(depressionBinary ~ doingWt + factor(BMIcat), 
                data = dat,
                family = binomial(link = "logit"))
summary(dep2.daw)
##################################################################################################
#add in other potential confounders
dep3.ltw <- glm(depressionBinary ~ likeTo + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race),
                data = dat,
                family = binomial(link = "logit"))
summary(dep3.ltw)

dep3.cow <- glm(depressionBinary ~ consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race), 
                data = dat,
                family = binomial(link = "logit"))
summary(dep3.cow)

dep3.daw <- glm(depressionBinary ~ doingWt + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race),
                data = dat,
                family = binomial(link = "logit"))
summary(dep3.daw)

#Models with all 3 of the components
dep1.all <- glm(depressionBinary ~ likeTo + doingWt +
                  consid,
                data = dat,
                family = binomial(link = "logit"))
summary(dep1.all)

dep2.all <- glm(depressionBinary ~ likeTo + doingWt +
                  consid + factor(BMIcat),
                data = dat,
                family = binomial(link = "logit"))
summary(dep2.all)

dep5.all <- glm(depressionBinary ~ likeTo + doingWt +
                  consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race),
                data = dat,
                family = binomial(link = "logit"))
summary(dep5.all)
```


```{r}
getOR <- function(mod){
  ors <- exp(mod$coefficients)[2:3]
  cis <- exp(confint(mod))[2:3,]
  modframe <- as.data.frame(cbind(ors, cis[,1], cis[,2]))
  names(modframe) <- c("ors", "lower", "upper")
  modframe$print <- paste(sprintf(as.numeric(modframe$ors), fmt = "%.2f"), "(",
                          sprintf(as.numeric(modframe$lower), fmt = "%.2f"), "-",
                          sprintf(as.numeric(modframe$upper), fmt = "%.2f"), ")")
  print(modframe$print[1])
  print(modframe$print[2])
}

getOR2 <- function(mod){
  ors <- exp(mod$coefficients)[2:5]
  cis <- exp(confint(mod))[2:5,]
  modframe <- as.data.frame(cbind(ors, cis[,1], cis[,2]))
  names(modframe) <- c("ors", "lower", "upper")
  modframe$print <- paste(sprintf(as.numeric(modframe$ors), fmt = "%.2f"), "(",
                          sprintf(as.numeric(modframe$lower), fmt = "%.2f"), "-",
                          sprintf(as.numeric(modframe$upper), fmt = "%.2f"), ")")
  print(modframe$print[1])
  print(modframe$print[2])
  print(modframe$print[3])
  print(modframe$print[4])
}


#unadjusted odds for depression
dep1.ltw <- svyglm(depressionBinary ~ likeTo, #ref = same
                design = svy,
                family = binomial(link = "logit"))
summary(dep1.ltw)
getOR(dep1.ltw)

dep1.cow <- svyglm(depressionBinary ~ consid, #ref = about right
                design = svy,
                family = binomial(link = "logit"))
getOR(dep1.cow)

dep1.daw <- svyglm(depressionBinary ~ doingWt, #ref = not doing anything
                design = svy,
                family = binomial(link = "logit"))

getOR2(dep1.daw)
################################################################################################
#add in BMI category
dep2.ltw <- svyglm(depressionBinary ~ likeTo + factor(BMIcat), 
                design = svy,
                family = binomial(link = "logit"))
getOR(dep2.ltw)

dep2.cow <- svyglm(depressionBinary ~ consid + factor(BMIcat), 
                design = svy,
                family = binomial(link = "logit"))
getOR(dep2.cow)

dep2.daw <- svyglm(depressionBinary ~ doingWt + factor(BMIcat), 
                design = svy,
                family = binomial(link = "logit"))
getOR2(dep2.daw)
##################################################################################################
#add in other potential confounders
dep3.ltw <- svyglm(depressionBinary ~ likeTo + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race),
                design = svy,
                family = binomial(link = "logit"))
getOR(dep3.ltw)

dep3.cow <- svyglm(depressionBinary ~ consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race), 
                design = svy,
                family = binomial(link = "logit"))
getOR(dep3.cow)

dep3.daw <- svyglm(depressionBinary ~ doingWt + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race),
                design = svy,
                family = binomial(link = "logit"))
getOR2(dep3.daw)

#Models with all 3 of the components
dep1.all <- glm(depressionBinary ~ likeTo + doingWt +
                  consid,
                data = dat,
                family = binomial(link = "logit"))
summary(dep1.all)

dep2.all <- glm(depressionBinary ~ likeTo + doingWt +
                  consid + factor(BMIcat),
                data = dat,
                family = binomial(link = "logit"))
summary(dep2.all)

dep5.all <- glm(depressionBinary ~ likeTo + doingWt +
                  consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race),
                data = dat,
                family = binomial(link = "logit"))
summary(dep5.all)
```



##Smoking
```{r, echo=FALSE, results = 'asis'}
#unadjusted
smk1.ltw <- multinom(smkStat ~ likeTo,
                     data = dat)
smk1.daw <- multinom(smkStat ~ doingWt,
                     data = dat)
smk1.cow <- multinom(smkStat ~ consid,
                     data = dat)

#adjust for BMI category
smk2.ltw <- multinom(smkStat ~ likeTo + factor(BMIcat),
                     data = dat)
smk2.daw <- multinom(smkStat ~ doingWt + factor(BMIcat),
                     data = dat)
smk2.cow <- multinom(smkStat ~ consid + factor(BMIcat),
                     data = dat)

#other adjustments
smk3.ltw <- multinom(smkStat ~ likeTo + factor(BMIcat) + factor(age4) + factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race) + phq9,
                     data = dat)
smk3.daw <- multinom(smkStat ~ doingWt + factor(BMIcat) + factor(age4) + factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race) + phq9,
                     data = dat)
smk3.cow <- multinom(smkStat ~ consid + factor(BMIcat) + factor(age4) + factor(Male) + factor(maritalstatus) + factor(edu) + factor(Income) + factor(Race) + phq9,
                     data = dat)


s1c <- tidy(smk1.cow, conf.int = T, exponentiate = TRUE)
s1l <- tidy(smk1.ltw, conf.int = T, exponentiate = TRUE)
s1d <- tidy(smk1.daw, conf.int = T, exponentiate = TRUE)

s2c <- tidy(smk2.cow, conf.int = T, exponentiate = TRUE)
s2l <- tidy(smk2.ltw, conf.int = T, exponentiate = TRUE)
s2d <- tidy(smk2.daw, conf.int = T, exponentiate = TRUE)

s3c <- tidy(smk3.cow, conf.int = T, exponentiate = TRUE)
s3l <- tidy(smk3.ltw, conf.int = T, exponentiate = TRUE)
s3d <- tidy(smk3.daw, conf.int = T, exponentiate = TRUE)

knitr::kable(s1c)
knitr::kable(s2c)
knitr::kable(s3c)

knitr::kable(s1l)
knitr::kable(s2l)
knitr::kable(s3l)

knitr::kable(s1d)
knitr::kable(s2d)
knitr::kable(s3d)

# summary(smk1.cow)
# summary(smk2.cow)
# summary(smk3.cow)
# 
# summary(smk1.ltw)
# summary(smk2.ltw)
# summary(smk3.ltw)
# 
# summary(smk1.daw)
# summary(smk2.daw)
# summary(smk3.daw)



```


```{r}
#unadjusted odds for drinkression
drink1.ltw <- svyglm(bingeDrk ~ likeTo, #ref = same
                design = svy,
                family = binomial(link = "logit"))
getOR(drink1.ltw)

drink1.cow <- svyglm(bingeDrk ~ consid, #ref = about right
                design = svy,
                family = binomial(link = "logit"))
getOR(drink1.cow)

drink1.daw <- svyglm(bingeDrk ~ doingWt, #ref = not doing anything
                design = svy,
                family = binomial(link = "logit"))
getOR2(drink1.daw)
################################################################################################
#add in BMI category
drink2.ltw <- svyglm(bingeDrk ~ likeTo + factor(BMIcat), 
                design = svy,
                family = binomial(link = "logit"))
getOR(drink2.ltw)

drink2.cow <- svyglm(bingeDrk ~ consid + factor(BMIcat), 
                design = svy,
                family = binomial(link = "logit"))
getOR(drink2.cow)

drink2.daw <- svyglm(bingeDrk ~ doingWt + factor(BMIcat), 
                design = svy,
                family = binomial(link = "logit"))
getOR2(drink2.daw)
##################################################################################################
#add in other potential confounders
drink3.ltw <- svyglm(bingeDrk ~ likeTo + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + 
                    factor(Income) + factor(Race) + factor(depressionBinary),
                design = svy,
                family = binomial(link = "logit"))
getOR(drink3.ltw)

drink3.cow <- svyglm(bingeDrk ~ consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) +
                    factor(Income) + factor(Race)+ factor(depressionBinary), 
                design = svy,
                family = binomial(link = "logit"))
getOR(drink3.cow)

drink3.daw <- svyglm(bingeDrk ~ doingWt + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) +
                    factor(Income) + factor(Race)+ factor(depressionBinary),
                design = svy,
                family = binomial(link = "logit"))
getOR2(drink3.daw)

#Models with all 3 of the components
drink1.all <- glm(bingeDrk ~ likeTo + doingWt +
                  consid,
                data = dat,
                family = binomial(link = "logit"))
summary(drink1.all)

drink2.all <- glm(bingeDrk ~ likeTo + doingWt +
                  consid + factor(BMIcat),
                data = dat,
                family = binomial(link = "logit"))
summary(drink2.all)

drink5.all <- glm(bingeDrk ~ likeTo + doingWt +
                  consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + 
                    factor(Income) + factor(Race)+ factor(depressionBinary),
                data = dat,
                family = binomial(link = "logit"))
summary(drink5.all)
```


#Binge Drinking = 5+ drinks at once (Never/Ever)
```{r}
#unadjusted odds for drinkression
drink1.ltw <- glm(bingeDrk ~ likeTo, #ref = same
                data = dat,
                family = binomial(link = "logit"))
summary(drink1.ltw)

drink1.cow <- glm(bingeDrk ~ consid, #ref = about right
                data = dat,
                family = binomial(link = "logit"))
summary(drink1.cow)

drink1.daw <- glm(bingeDrk ~ doingWt, #ref = not doing anything
                data = dat,
                family = binomial(link = "logit"))
summary(drink1.daw)
################################################################################################
#add in BMI category
drink2.ltw <- glm(bingeDrk ~ likeTo + factor(BMIcat), 
                data = dat,
                family = binomial(link = "logit"))
summary(drink2.ltw)

drink2.cow <- glm(bingeDrk ~ consid + factor(BMIcat), 
                data = dat,
                family = binomial(link = "logit"))
summary(drink2.cow)

drink2.daw <- glm(bingeDrk ~ doingWt + factor(BMIcat), 
                data = dat,
                family = binomial(link = "logit"))
summary(drink2.daw)
##################################################################################################
#add in other potential confounders
drink3.ltw <- glm(bingeDrk ~ likeTo + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + 
                    factor(Income) + factor(Race) + factor(depressionBinary),
                data = dat,
                family = binomial(link = "logit"))
summary(drink3.ltw)

drink3.cow <- glm(bingeDrk ~ consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) +
                    factor(Income) + factor(Race)+ factor(depressionBinary), 
                data = dat,
                family = binomial(link = "logit"))
summary(drink3.cow)

drink3.daw <- glm(bingeDrk ~ doingWt + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) +
                    factor(Income) + factor(Race)+ factor(depressionBinary),
                data = dat,
                family = binomial(link = "logit"))
summary(drink3.daw)

#Models with all 3 of the components
drink1.all <- glm(bingeDrk ~ likeTo + doingWt +
                  consid,
                data = dat,
                family = binomial(link = "logit"))
summary(drink1.all)

drink2.all <- glm(bingeDrk ~ likeTo + doingWt +
                  consid + factor(BMIcat),
                data = dat,
                family = binomial(link = "logit"))
summary(drink2.all)

drink5.all <- glm(bingeDrk ~ likeTo + doingWt +
                  consid + factor(BMIcat) + factor(age4) +
                  factor(Male) + factor(maritalstatus) + factor(edu) + 
                    factor(Income) + factor(Race)+ factor(depressionBinary),
                data = dat,
                family = binomial(link = "logit"))
summary(drink5.all)


```




```{r, echo=FALSE, eval = FALSE, include = FALSE}

#create a bootstrap replicate weight set
des2<-as.svrepdesign(svy, type="bootstrap" , replicates=10)

#Now I fit the model, this is screwy looking
mfit <- withReplicates(des2, quote(coef(multinom(smkStat ~ likeTo,
                                               weights = .weights,
                                               trace = F))))

#get the betas
mfitcoef <- data.frame(matrix(attr(attr(mfit, "var"), "means"), nrow = 2, ncol = 3, byrow = F))
#names(mfitcoef)<-names(coef(ex1)[-1])

#odds ratios
round(exp(mfitcoef), 3)

#get the covariance matrix for the betas
vcov <- matrix(attr(mfit, "var"), nrow=6, ncol=6)

#now get the standard errors
se <- as.data.frame(diag(vcov), nrow = 2, ncol = 3, byrow = F)
se <- matrix(unlist(t(se)), byrow = F, nrow = 2, ncol = 3)

#95% CI
upper <- mfitcoef + 1.96*se
lower <- mfitcoef - 1.96*se

#get the z tests by using the coefficients and the standard errors (diag(vcov))
z <- as.vector(mfitcoef/sqrt(diag(vcov)))
round(z, 2)

#p values
pvals <- round((1-pnorm(abs(as.matrix(z)),0,1))*2,4)
round(pvals, 3)

#finally, but everything into one (useable!) data frame
#name, beta, se, z test, p value, OR, lower, upper
result <- matrix(nrow = length(levels(dat$likeTo))*2, ncol = 9)
result <- as.data.frame(result)
names(result) <- c("name", "beta", "se", "z test", "p value", "OR", "lower", "upper", "model")

#now fill it in!
result$name <- c(rep("intercept",2),
                 rep(levels(dat$likeTo)[2],2),
                 rep(levels(dat$likeTo)[3],2))

#denoting which smklevel is predicted
result$model <- rep(c(1,2), 3)
result$beta <- as.vector(as.matrix(mfitcoef))
result$se <- as.vector(as.matrix(se))
result$`z test` <- z


```



```{r}
#Food security
options(scipen = 0)
fs.ltw <- multinom(likeTo ~ fsWithHunger, data = dat)
broom::tidy(fs.ltw, conf.int = T, exponentiate = T)

fs.ltw <- multinom(likeTo ~ factor(hhFScat), data = dat)
broom::tidy(fs.ltw, conf.int = T, exponentiate = T)


fs.ltw.bmi <- multinom(likeTo ~ fsWithHunger + factor(BMIcat), data = dat)
broom::tidy(fs.ltw.bmi, conf.int = T, exponentiate = T)

fs.ltw.bmi <- multinom(likeTo ~ factor(hhFScat)+ factor(BMIcat), data = dat)
broom::tidy(fs.ltw.bmi, conf.int = T, exponentiate = T)


fs.ltw.male<- multinom(likeTo ~ fsWithHunger + factor(BMIcat) + Male, data = dat)
broom::tidy(fs.ltw.male, conf.int = T, exponentiate = T)

fs.ltw.male <- multinom(likeTo ~ factor(hhFScat)+ factor(BMIcat) + Male, data = dat)
broom::tidy(fs.ltw.male, conf.int = T, exponentiate = T)

fs.ltw.race<- multinom(likeTo ~ fsWithHunger + factor(BMIcat) + Male + factor(Race), data = dat)
broom::tidy(fs.ltw.race, conf.int = T, exponentiate = T)

fs.ltw.race <- multinom(likeTo ~ factor(hhFScat)+ factor(BMIcat) + Male + factor(Race), data = dat)
broom::tidy(fs.ltw.race, conf.int = T, exponentiate = T)

fs.ltw.inc <- multinom(likeTo ~ fsWithHunger + factor(BMIcat) + Male + factor(Race) +factor(Income), data = dat)
broom::tidy(fs.ltw.inc, conf.int = T, exponentiate = T)

fs.ltw.inc <- multinom(likeTo ~ factor(hhFScat)+ factor(BMIcat) + Male + factor(Race)+factor(Income), data = dat)
broom::tidy(fs.ltw.inc, conf.int = T, exponentiate = T)

```








